FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt ./

RUN apt-get update && apt-get install -y ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir -r requirements.txt \
    && mkdir ./completed ./uploads

ENTRYPOINT [ "demucs" ]
VOLUME [ "/app/completed", "/app/uploads" ]
EXPOSE 80