# Generated by Django 6.0 on 2026-01-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='output_format',
            field=models.CharField(choices=[('mp3', 'MP3 (Smaller files)'), ('wav', 'WAV (Lossless quality)')], default='mp3', help_text='Output audio format', max_length=10),
        ),
    ]
